/*HEADER FILE COM AS FUNCOES NECESSARIAS PARA TODO O CODIGO DO PROJETO*/
void			AtribuiResultado			(modalidade m, int a, int b);
void			CalculaAtteDef				(modalidade *mod);
void			CalculaMediaGolosCasa		(modalidade *mod);
void			CalculaMediaGolosFora		(modalidade *mod);
void			CalculaOddsIniciais			(modalidade *mod);
void			CriaJogos					(modalidade *mod);
void			Definicoes					(modalidade *mod, int *quantidade);
int				EscolheJogo					(modalidade *mod);
int				EscolheModalidade			(modalidade *mod, int *quantidade);
void			FicheiroExiste				(char nomeficheiro[], FILE **fd);
void			FicheiroImprimir			(char nomeficheiro[]);
void			FicheiroLeData				(modalidade *mod, int *quantidadeMods);
int				FicheiroLinhas				(char nomeficheiro[]);
void			GereJogo					(modalidade *mod, int *quantidade);
void			GerirSaldo					(int *saldo);
void			ListarTudo					(modalidade *mod, int *quantidade);
void			LimpaEcra					(void);
void			Poisson						(modalidade *mod);
int				ResultadoRandom				(modalidade *mod);
int				SeedAleatoria				(void);
int				SimulaComBaseNasOddsCasa	(modalidade *mod, int indexJogo);
int				SimulaComBaseNasOddsFora	(modalidade *mod, int indexJogo);